name: ceshi openwrt

on:
  repository_dispatch:
  workflow_dispatch:
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  Feeds_path: feeds.conf.default
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: yilai
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential 
        sudo apt install -y bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gettext gcc-multilib g++-multilib
        sudo apt install -y git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev
        sudo apt install -y libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libncurses-dev libpython3-dev libreadline-dev 
        sudo apt install -y libssl-dev libtool llvm lrzsz genisoimage msmtp ninja-build p7zip p7zip-full patch pkgconf python3 
        sudo apt install -y python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo 
        sudo apt install -y uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo -E timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH lede
        
    - name: load feeds
      run: |
         [ -e files ] && mv files lede/files
         [ -e $Feeds_path ] && mv $Feeds_path lede/feeds.conf.default
    
    - name: Update feeds
      run: cd lede && ./scripts/feeds update -a

    - name: Install feeds
      run: cd lede && ./scripts/feeds install -a
      
    #- name: load config
     # run: |
        # [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
         
    #- name: Download package
    #   id: package
     #  run: |
      #   cd lede
       #  make defconfig
        # make download -j8
        # find dl -size -1024c -exec ls -l {} \;
        # find dl -size -1024c -exec rm -f {} \;
         
   # - name: make ipk
     #   run: make package/luci-app-wol/compile V=s
