name: ceshi openwrt

on:
  repository_dispatch:
  workflow_dispatch:
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  Feeds_path: feeds.conf.default
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    

        
    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH lede
        
    - name: load feeds
      run: |
         [ -e files ] && mv files lede/files
         [ -e $Feeds_path ] && mv $Feeds_path lede/feeds.conf.default
   
      
    - name: load config
      run: |
         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
         
    - name: Download package
        id: package
        run: |
          cd lede
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
         
   # - name: make ipk
     #   run: make package/luci-app-wol/compile V=s
